import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'


const polymath= localFont({
  src: '../public/fonts/PolymathDemo-Semibold.ttf',
  variable: '--font-polymath',
})


// const polymath= localFont({ src: 'fonts/PolymathDemo-Semibold.otf' })
// const polymath= localFont({ src: 'fonts/PolymathDemo-Semibold.ttf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={polymath.className}>{children}</body>
    </html>
  );
}
